

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    name:

  jpa:
    hibernate:
      ddl-auto: update
#test

