

spring:
  datasource:
    url: jdbc:mysql:${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: blog

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  #test
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}

